"""
HOPE Router

Routes detected intents to the
appropriate HOPE module.
"""

from assistant.commands import process_command

from core.help import show_help
from core.system import get_system_status
from core.diagnostics import run_diagnostics

from core.recovery import get_recovery_report

from core.recovery_intelligence import (
    get_recovery_intelligence_report,
    detect_recovery_patterns,
    get_pattern_summary,
    get_module_reliability,
    get_recovery_trend_report,
    get_predictive_failure_report,
)

from core.recovery_log import (
    format_recovery_history,
    get_last_recovery,
)

from memory.manager import remember, recall

from conversation.manager import get_last_user_message
from conversation.summary import summarize_conversation

from knowledge.engine import search_knowledge

from reasoning.engine import reason

from goal.engine import process_goal
from goal.roadmap import get_roadmap
from goal.planner import get_today_plan
from goal.progress import (
    get_progress,
    get_next_topic,
    mark_completed,
)


def route(result):
    """
    Route the detected intent to the
    appropriate HOPE module.

    Parameters:
        result (dict): Result produced by the Brain Engine.

    Returns:
        str: Response generated by the appropriate module.
    """

    intent = result.get(
        "intent",
        "UNKNOWN"
    )

    command = result.get(
        "command",
        ""
    ).strip().lower()

    print(f"[Router] Intent : {intent}")

    # ========================================================
    # BASIC CLI / SYSTEM COMMANDS
    # ========================================================

    if intent in [
        "GREETING",
        "TIME_REQUEST",
        "DATE_REQUEST",
        "ABOUT",
        "VERSION",
        "COPYRIGHT",
    ]:

        return process_command(command)

    # ========================================================
    # SYSTEM STATUS / DIAGNOSTICS
    # ========================================================

    elif intent == "STATUS":

        if command in [
            "system diagnostics",
            "diagnostics",
            "run diagnostics",
            "check system",
        ]:

            print(
                "[Router] Running Diagnostics"
            )

            return run_diagnostics()

        return get_system_status()

    # ========================================================
    # SYSTEM HEALTH INTELLIGENCE
    # ========================================================

    elif intent == "HEALTH":

        from core.diagnostics import get_health_report

        print(
            "[Router] Running Health Intelligence"
        )

        return get_health_report()

    # ========================================================
    # AUTOMATIC RECOVERY
    # ========================================================

    elif intent == "RECOVERY":

        print(
            "[Router] Running Automatic Recovery"
        )

        return get_recovery_report()

    # ========================================================
    # RECOVERY INTELLIGENCE
    # ========================================================

    elif intent == "RECOVERY_INTELLIGENCE":

        print(
            "[Router] Running Recovery Intelligence"
        )

        return get_recovery_intelligence_report()

    # ========================================================
    # RECOVERY PATTERN INTELLIGENCE
    # ========================================================

    elif intent == "RECOVERY_PATTERNS":

        print(
            "[Router] Running Recovery Pattern Intelligence"
        )

        patterns = detect_recovery_patterns()

        summary = get_pattern_summary()

        reliability = get_module_reliability()

        lines = [
            "🧩 HOPE Recovery Pattern Intelligence",
            "",
            f"Overall Pattern : "
            f"{summary.get('overall_pattern', 'UNKNOWN')}",
            "",
            f"Modules Analyzed : "
            f"{summary.get('total_modules', 0)}",
            "",
        ]

        # ----------------------------------------------------
        # Recovery Patterns
        # ----------------------------------------------------

        if patterns:

            lines.append(
                "📊 Recovery Patterns"
            )

            for pattern in patterns:

                lines.append(
                    f"• {pattern.get('module', 'Unknown')} "
                    f"→ {pattern.get('pattern', 'UNKNOWN')}"
                )

                lines.append(
                    f"  Events      : "
                    f"{pattern.get('events', 0)}"
                )

                lines.append(
                    f"  Successful  : "
                    f"{pattern.get('successful', 0)}"
                )

                lines.append(
                    f"  Failed      : "
                    f"{pattern.get('failed', 0)}"
                )

                lines.append(
                    f"  Success Rate: "
                    f"{pattern.get('success_rate', 0.0):.2f}%"
                )

                description = pattern.get(
                    "description"
                )

                if description:

                    lines.append(
                        f"  {description}"
                    )

                lines.append("")

        else:

            lines.append(
                "No recovery patterns detected."
            )

            lines.append("")

        # ----------------------------------------------------
        # Module Reliability
        # ----------------------------------------------------

        if reliability:

            lines.append(
                "🛡️ Module Reliability"
            )

            for module in reliability:

                lines.append(
                    f"• {module.get('module', 'Unknown')}"
                )

                lines.append(
                    f"  Events      : "
                    f"{module.get('events', 0)}"
                )

                lines.append(
                    f"  Successful  : "
                    f"{module.get('successful', 0)}"
                )

                lines.append(
                    f"  Failed      : "
                    f"{module.get('failed', 0)}"
                )

                lines.append(
                    f"  Success Rate: "
                    f"{module.get('success_rate', 0.0):.2f}%"
                )

                lines.append("")

        return "\n".join(lines)

    # ========================================================
    # RECOVERY TREND INTELLIGENCE
    # ========================================================

    elif intent == "RECOVERY_TRENDS":

        print(
            "[Router] Running Recovery Trend Intelligence"
        )

        return get_recovery_trend_report()

    # ========================================================
    # PREDICTIVE FAILURE INTELLIGENCE
    # ========================================================

    elif intent == "PREDICTIVE_FAILURE":

        print(
            "[Router] Running Predictive Failure Intelligence"
        )

        return get_predictive_failure_report()

    # ========================================================
    # RECOVERY HISTORY
    # ========================================================

    elif intent == "RECOVERY_HISTORY":

        print(
            "[Router] Showing Recovery History"
        )

        return format_recovery_history()

    # ========================================================
    # LAST RECOVERY
    # ========================================================

    elif intent == "LAST_RECOVERY":

        print(
            "[Router] Showing Last Recovery"
        )

        event = get_last_recovery()

        if event is None:

            return (
                "📜 HOPE Recovery History\n\n"
                "No recovery events have been "
                "recorded yet."
            )

        return (
            "🔧 Last HOPE Recovery\n"
            "\n"
            f"Time    : "
            f"{event.get('time', 'Unknown')}\n"
            f"Module  : "
            f"{event.get('module', 'Unknown')}\n"
            f"Failure : "
            f"{event.get('failure', 'Unknown')}\n"
            f"Action  : "
            f"{event.get('action', 'Unknown')}\n"
            f"Result  : "
            f"{event.get('result', 'Unknown')}\n"
            f"Health  : "
            f"{event.get('health_before', 'Unknown')}"
            f" → "
            f"{event.get('health_after', 'Unknown')}"
        )

    # ========================================================
    # HELP ENGINE
    # ========================================================

    elif intent == "HELP":

        if command == "help":

            return show_help()

        if command in [
            "commands",
            "show commands",
            "available commands",
        ]:

            return show_help()

        parts = command.split(
            " ",
            1
        )

        if len(parts) == 2:

            category = parts[1].strip()

            return show_help(category)

        return show_help()

    # ========================================================
    # MEMORY SAVE
    # ========================================================

    elif intent == "MEMORY_SAVE":

        if (
            "key" in result
            and "value" in result
        ):

            key = result["key"]
            value = result["value"]

        else:

            parts = command.split(
                " ",
                2
            )

            if len(parts) != 3:

                return (
                    "Usage: remember "
                    "<key> <value>"
                )

            key = parts[1]
            value = parts[2]

        print(
            "[Router] Saving Memory"
        )

        print(
            f"[Router] Key   : {key}"
        )

        print(
            f"[Router] Value : {value}"
        )

        return remember(
            key,
            value
        )

    # ========================================================
    # MEMORY RECALL
    # ========================================================

    elif intent == "MEMORY_RECALL":

        parts = command.split(
            " ",
            1
        )

        if len(parts) != 2:

            return (
                "Usage: recall <key>"
            )

        key = parts[1]

        print(
            "[Router] Recalling Memory"
        )

        print(
            f"[Router] Key : {key}"
        )

        value = recall(key)

        if value is not None:

            return value

        return (
            "I don't remember that."
        )

    # ========================================================
    # GOAL DETECTION
    # ========================================================

    elif intent == "GOAL":

        goal_result = process_goal(
            command
        )

        if goal_result is None:

            return (
                "I couldn't identify "
                "your goal."
            )

        goal = goal_result["goal"]

        return get_roadmap(goal)

    # ========================================================
    # GOAL RECALL
    # ========================================================

    elif intent == "GOAL_RECALL":

        goal = recall(
            "current_goal"
        )

        if goal is None:

            return (
                "You haven't told me "
                "your goal yet."
            )

        return (
            "🎯 Your current goal is:\n\n"
            f"{goal}"
        )

    # ========================================================
    # STUDY PLAN
    # ========================================================

    elif intent == "STUDY_PLAN":

        goal = recall(
            "current_goal"
        )

        if goal is None:

            return (
                "You haven't set a goal yet.\n\n"
                "Try saying:\n"
                "'I want to become AI Engineer'"
            )

        return get_today_plan(
            goal
        )

    # ========================================================
    # PROGRESS
    # ========================================================

    elif intent == "PROGRESS":

        goal = recall(
            "current_goal"
        )

        if goal is None:

            return (
                "You haven't set a goal yet."
            )

        return get_progress(
            goal
        )

    # ========================================================
    # NEXT TOPIC
    # ========================================================

    elif intent == "NEXT_TOPIC":

        goal = recall(
            "current_goal"
        )

        if goal is None:

            return (
                "You haven't set a goal yet."
            )

        topic = get_next_topic(
            goal
        )

        if topic is None:

            return (
                "🎉 Congratulations!\n"
                "You have completed your roadmap."
            )

        return (
            "📘 Your next topic is:\n\n"
            f"{topic}"
        )

    # ========================================================
    # MARK COMPLETED
    # ========================================================

    elif intent == "MARK_COMPLETED":

        goal = recall(
            "current_goal"
        )

        if goal is None:

            return (
                "You haven't set a goal yet."
            )

        topic = (
            command
            .replace(
                "mark",
                "",
                1
            )
            .replace(
                "completed",
                "",
                1
            )
            .strip()
            .title()
        )

        if not topic:

            return (
                "Usage: "
                "mark <topic> completed"
            )

        message = mark_completed(
            goal,
            topic
        )

        progress = get_progress(
            goal
        )

        return (
            f"{message}\n\n"
            f"{progress}"
        )

    # ========================================================
    # LAST USER MESSAGE
    # ========================================================

    elif intent == "LAST_USER_MESSAGE":

        last_message = get_last_user_message(
            skip_current=True
        )

        if last_message:

            return (
                f'You said: '
                f'"{last_message}"'
            )

        return (
            "I don't remember you saying "
            "anything yet."
        )

    # ========================================================
    # CONVERSATION SUMMARY
    # ========================================================

    elif intent == "CONVERSATION_SUMMARY":

        return summarize_conversation()

    # ========================================================
    # KNOWLEDGE SEARCH
    # ========================================================

    elif intent == "KNOWLEDGE_SEARCH":

        response = reason(
            command
        )

        if response is not None:

            return response

        return search_knowledge(
            command
        )

    # ========================================================
    # COMPARISON
    # ========================================================

    elif intent == "COMPARE":

        response = reason(
            command
        )

        if response is not None:

            return response

        return (
            "I couldn't compare "
            "those topics."
        )

    # ========================================================
    # RECOMMENDATION
    # ========================================================

    elif intent == "RECOMMEND":

        response = reason(
            command
        )

        if response is not None:

            return response

        return (
            "I don't have a recommendation."
        )

    # ========================================================
    # EXIT
    # ========================================================

    elif intent == "EXIT":

        return "Goodbye!"

    # ========================================================
    # UNKNOWN
    # ========================================================

    else:

        return process_command(
            command
        )