"""
HOPE Router

Routes detected intents to the
appropriate HOPE module.
"""

from assistant.commands import process_command

from core.help import show_help
from core.system import get_system_status
from core.diagnostics import run_diagnostics

from core.recovery import get_recovery_report

from core.recovery_intelligence import (
    get_recovery_intelligence_report,
    detect_recovery_patterns,
    get_pattern_summary,
    get_module_reliability,
    get_recovery_trend_report,
    get_predictive_failure_report,
)

from core.recovery_log import (
    format_recovery_history,
    get_last_recovery,
)

from memory.manager import (
    remember,
    recall,
    forget,
)

from conversation.manager import get_last_user_message
from conversation.summary import summarize_conversation

from knowledge.engine import search_knowledge

from reasoning.engine import reason

from goal.engine import process_goal
from goal.roadmap import get_roadmap
from goal.planner import get_today_plan
from goal.progress import (
    get_progress,
    get_next_topic,
    mark_completed,
)

from core.predictive_intelligence import (
    get_system_prediction,
    get_predictive_report,
    get_module_predictions,
    get_predictive_recommendation,
    get_predictive_signals,
    get_predictive_action_decision,
    get_predictive_action_decisions,
)


def route(result):
    """
    Route the detected intent to the
    appropriate HOPE module.

    Parameters:
        result (dict): Result produced by the Brain Engine.

    Returns:
        str: Response generated by the appropriate module.
    """

    intent = result.get("intent", "UNKNOWN")
    command = result.get("command", "").strip().lower()

    print(f"[Router] Intent : {intent}")

    # ========================================================
    # BASIC CLI / SYSTEM COMMANDS
    # ========================================================

    if intent in [
        "GREETING",
        "TIME_REQUEST",
        "DATE_REQUEST",
        "ABOUT",
        "VERSION",
        "COPYRIGHT",
    ]:
        return process_command(command)

    # ========================================================
    # SYSTEM STATUS / DIAGNOSTICS
    # ========================================================

    elif intent == "STATUS":

        # ----------------------------------------------------
        # Detailed Diagnostics
        # ----------------------------------------------------

        if command in [
            "system diagnostics",
            "diagnostics",
            "run diagnostics",
            "check system",
        ]:
            print("[Router] Running Diagnostics")

            return run_diagnostics()

        # ----------------------------------------------------
        # Normal System Status
        # ----------------------------------------------------

        return get_system_status()

    # ========================================================
    # SYSTEM HEALTH INTELLIGENCE
    # ========================================================

    elif intent == "HEALTH":

        from core.diagnostics import get_health_report

        print("[Router] Running Health Intelligence")

        return get_health_report()

    # ========================================================
    # RECOVERY INTELLIGENCE
    # ========================================================

    elif intent == "RECOVERY_INTELLIGENCE":

        print("[Router] Running Recovery Intelligence")

        return get_recovery_intelligence_report()

    # ========================================================
    # RECOVERY PATTERN INTELLIGENCE
    # ========================================================

    elif intent == "RECOVERY_PATTERNS":

        print("[Router] Running Recovery Pattern Intelligence")

        patterns = detect_recovery_patterns()
        summary = get_pattern_summary()
        reliability = get_module_reliability()
        trend = get_recovery_trend_report()
        predictive_failure = get_predictive_failure_report()

        lines = [
            "🧩 HOPE Recovery Pattern Intelligence",
            "",
            f"Overall Pattern : {summary.get('overall_pattern', 'UNKNOWN')}",
            f"Modules Analyzed : {summary.get('total_modules', 0)}",
            "",
            "Recovery Patterns:",
        ]

        if patterns:
            if isinstance(patterns, dict):
                for module, pattern in patterns.items():
                    lines.append(f"• {module}: {pattern}")
            else:
                for pattern in patterns:
                    lines.append(f"• {pattern}")
        else:
            lines.append("• No recovery patterns detected.")

        lines.extend([
            "",
            "Module Reliability:",
        ])

        if reliability:
            if isinstance(reliability, dict):
                for module, value in reliability.items():
                    lines.append(f"• {module}: {value}")
            else:
                lines.append(str(reliability))
        else:
            lines.append("• No module reliability data available.")

        lines.extend([
            "",
            "Recovery Trend:",
            str(trend),
            "",
            "Predictive Failure:",
            str(predictive_failure),
        ])

        return "\n".join(lines).rstrip()

    # ========================================================
    # PREDICTIVE INTELLIGENCE
    # ========================================================

    elif intent == "PREDICTIVE_STATUS":

        print("[Router] Running Predictive Status")

        system = get_system_prediction()

        return (
            "🔮 HOPE Predictive Status\n\n"
            f"Overall Risk : {system.get('overall_risk', 'UNKNOWN')}\n"
            f"Risk Score   : {system.get('risk_score', 0)}/100\n"
            f"Confidence   : {system.get('confidence', 'UNKNOWN')}\n"
            f"Action       : {system.get('action', 'UNKNOWN')}\n"
            f"Priority     : {system.get('priority', 'UNKNOWN')}\n"
            f"Reason       : {system.get('action_reason', 'No action reason available.')}"
        )

    # ========================================================
    # PREDICTIVE RISK
    # ========================================================

    elif intent == "PREDICTIVE_RISK":

        print("[Router] Running Predictive Risk Assessment")

        system = get_system_prediction()

        return (
            "🔮 HOPE Predictive Risk\n\n"
            f"Overall Risk : {system.get('overall_risk', 'UNKNOWN')}\n"
            f"Risk Score   : {system.get('risk_score', 0)}/100\n"
            f"Confidence   : {system.get('confidence', 'UNKNOWN')}\n"
            f"Critical     : {system.get('critical', 0)}\n"
            f"High         : {system.get('high', 0)}\n"
            f"Medium       : {system.get('medium', 0)}\n"
            f"Insufficient : {system.get('insufficient_data', 0)}\n"
            f"Action       : {system.get('action', 'UNKNOWN')}\n"
            f"Priority     : {system.get('priority', 'UNKNOWN')}\n"
            f"Reason       : {system.get('action_reason', 'No action reason available.')}"
        )

    # ========================================================
    # PREDICTIVE REPORT
    # ========================================================

    elif intent == "PREDICTIVE_REPORT":

        print("[Router] Running Predictive Intelligence Report")

        return get_predictive_report()

    # ========================================================
    # MODULE RISK
    # ========================================================

    elif intent == "MODULE_RISK":

        print("[Router] Running Module Risk Assessment")

        predictions = get_module_predictions()

        if not predictions:
            return "🔮 No predictive module data is available yet."

        lines = [
            "🔮 HOPE Module Risk Assessment",
            "",
        ]

        for item in predictions:

            lines.extend([
                f"• {item.get('module', 'Unknown Module')}",
                f"  Risk Score : {item.get('risk_score', 0)}/100",
                f"  Risk       : {item.get('risk', 'UNKNOWN')}",
                f"  Confidence : {item.get('confidence', 'UNKNOWN')}",
                f"  Pattern    : {item.get('pattern', 'UNKNOWN')}",
                f"  Trend      : {item.get('trend', 'UNKNOWN')}",
                f"  Action     : {item.get('action', 'UNKNOWN')}",
                f"  Priority   : {item.get('priority', 'UNKNOWN')}",
                "",
            ])

        return "\n".join(lines).rstrip()

    # ========================================================
    # PREDICTIVE SYSTEM HEALTH
    # ========================================================

    elif intent == "SYSTEM_HEALTH":

        print("[Router] Running Predictive System Health")

        signals = get_predictive_signals()

        health = signals.get(
            "overall_health",
            "UNKNOWN"
        )

        module_health = signals.get(
            "health",
            {}
        )

        return (
            "🩺 HOPE Predictive System Health\n\n"
            f"Overall Health : {health}\n"
            f"Modules Checked: {len(module_health)}\n"
            f"Overall Trend  : {signals.get('overall_trend', 'UNKNOWN')}"
        )

    # ========================================================
    # PREDICTIVE DECISION — 6E-2
    # ========================================================

    elif intent == "PREDICTIVE_DECISION":

        print("[Router] Running Predictive Decision Routing")

        decisions = get_predictive_action_decisions()

        if not decisions:
            return (
                "🧭 HOPE Predictive Decision\n\n"
                "No predictive decision data is available yet."
            )

        # Identify an explicitly requested module when possible.
        selected = None

        module_aliases = {
            "knowledge engine": "Knowledge Engine",
            "brain engine": "Brain Engine",
            "context engine": "Context Engine",
            "goal engine": "Goal Engine",
            "memory engine": "Memory Engine",
            "planner engine": "Planner Engine",
            "progress engine": "Progress Engine",
            "reasoning engine": "Reasoning Engine",
        }

        for alias, module_name in module_aliases.items():
            if alias in command:
                selected = next(
                    (
                        item for item in decisions
                        if item.get("module") == module_name
                    ),
                    None,
                )
                if selected is not None:
                    break

        # If no module was specified, select the highest-priority
        # predictive decision without changing the decision itself.
        if selected is None:
            priority_order = {
                "CRITICAL": 4,
                "HIGH": 3,
                "MEDIUM": 2,
                "LOW": 1,
            }
            selected = max(
                decisions,
                key=lambda item: (
                    priority_order.get(item.get("priority"), 0),
                    item.get("risk_score", 0),
                ),
            )

        # 6E-2 presentation cleanup only.
        # The 6D predictive engine and 6E-1 decision object remain unchanged.
        explanation = str(
            selected.get(
                "explanation",
                "No predictive explanation is available."
            )
        )

        # 6E-2 presentation cleanup only.
        # This does not modify the underlying predictive decision.
        explanation = (
            explanation
            .replace("monitoringis", "monitoring is")
            .replace("predictionshould", "prediction should")
            .replace("historicaldata", "historical data")
            .replace("areliable", "a reliable")
            .replace("Dataquality", "Data quality")
            .replace("dataquality", "data quality")
            .replace("islimited", "is limited")
            .replace("Continuemonitoring", "Continue monitoring")
            .replace("monitoringKnowledge", "monitoring Knowledge")
            .replace("orfailures", "or failures")
            .replace("monitoringknowledge", "monitoring knowledge")
        )

        safety_reason = str(
            selected.get(
                "safety_reason",
                "No safety reason available."
            )
        )

        return (
            "🧭 HOPE Predictive Decision\n\n"
            f"Module       : {selected.get('module', 'Unknown')}\n"
            f"Risk         : {selected.get('risk', 'UNKNOWN')}\n"
            f"Risk Score   : {selected.get('risk_score', 0)}/100\n"
            f"Confidence   : {selected.get('confidence', 'UNKNOWN')}\n"
            f"Data Quality : {selected.get('data_quality', 'NO_DATA')}\n"
            f"Action       : {selected.get('action', 'UNKNOWN')}\n"
            f"Priority     : {selected.get('priority', 'UNKNOWN')}\n"
            f"Mode         : {selected.get('mode', 'UNKNOWN')}\n"
            f"Status       : {selected.get('status', 'UNKNOWN')}\n\n"
            "Safety:\n"
            f"Level        : {selected.get('safety_level', 'UNKNOWN')}\n"
            f"Execution    : {selected.get('execution_allowed', False)}\n"
            f"Automatic    : {selected.get('automatic_action_allowed', False)}\n\n"
            "Decision:\n"
            f"{explanation}\n\n"
            "Safety Reason:\n"
            f"{safety_reason}"
        )

    # ========================================================
    # PREDICTIVE RECOMMENDATION
    # ========================================================

    elif intent == "PREDICTIVE_RECOMMENDATION":

        print("[Router] Running Predictive Recommendation")

        recommendation = get_predictive_recommendation()

        return (
            "💡 HOPE Predictive Recommendation\n\n"
            f"Risk Level : {recommendation.get('risk', 'UNKNOWN')}\n"
            f"Action     : {recommendation.get('action', 'UNKNOWN')}\n\n"
            "Recommendation:\n"
            f"{recommendation.get('message', 'No recommendation available.')}"
        )

    # ========================================================
    # PREDICTIVE EXPLANATION
    # ========================================================

    elif intent == "PREDICTIVE_EXPLANATION":

        print("[Router] Running Predictive Explanation")

        predictions = get_module_predictions()

        if not predictions:
            return (
                "🔎 HOPE Predictive Explanation\n\n"
                "No predictive module data is available yet."
            )

        # Try to identify a module explicitly mentioned
        # in the user's command.
        selected = None

        module_aliases = {
            "knowledge engine": "Knowledge Engine",
            "brain engine": "Brain Engine",
            "context engine": "Context Engine",
            "goal engine": "Goal Engine",
            "memory engine": "Memory Engine",
            "planner engine": "Planner Engine",
            "progress engine": "Progress Engine",
            "reasoning engine": "Reasoning Engine",
        }

        for alias, module_name in module_aliases.items():

            if alias in command:

                for item in predictions:

                    if item.get("module") == module_name:

                        selected = item
                        break

                if selected is not None:
                    break

        # If no module was named, select the highest-priority
        # available prediction.
        if selected is None:

            risk_order = {
                "CRITICAL": 4,
                "HIGH": 3,
                "MEDIUM": 2,
                "LOW": 1,
                "INSUFFICIENT_DATA": 0,
            }

            selected = max(
                predictions,
                key=lambda item: (
                    risk_order.get(
                        item.get("risk"),
                        0
                    ),
                    item.get(
                        "risk_score",
                        0
                    ),
                ),
            )

        evidence = selected.get(
            "evidence",
            []
        )

        lines = [
            "🔎 HOPE Predictive Explanation",
            "",
            f"Module       : {selected.get('module', 'Unknown')}",
            f"Risk         : {selected.get('risk', 'UNKNOWN')}",
            f"Risk Score   : {selected.get('risk_score', 0)}/100",
            f"Confidence   : {selected.get('confidence', 'UNKNOWN')}",
            f"Data Quality : {selected.get('data_quality', 'NO_DATA')}",
            f"Quality Score: {selected.get('data_quality_score', 0)}/100",
            f"Reliable     : {selected.get('data_quality_reliable', False)}",
            f"Action       : {selected.get('action', 'UNKNOWN')}",
            f"Priority     : {selected.get('priority', 'UNKNOWN')}",
            "",
        ]

        if evidence:

            lines.append("Evidence:")

            for evidence_item in evidence:
                lines.append(
                    f"  • {evidence_item}"
                )

            lines.append("")

        explanation = selected.get(
            "explanation",
            "No predictive explanation is available."
        )

        # ----------------------------------------------------
        # Predictive explanation presentation cleanup
        # ----------------------------------------------------
        # Normalize legacy joined words at the Router boundary.
        # The predictive engine is the source of truth; this
        # cleanup only protects the user-facing presentation.
        explanation = (
            str(explanation)
            .replace("monitoringis", "monitoring is")
            .replace("predictionshould", "prediction should")
            .replace("historicaldata", "historical data")
            .replace("areliable", "a reliable")
            .replace("Dataquality", "Data quality")
            .replace("dataquality", "data quality")
            .replace("islimited", "is limited")
            .replace("Continuemonitoring", "Continue monitoring")
            .replace("monitoringKnowledge", "monitoring Knowledge")
            .replace("orfailures", "or failures")
            .replace("dataquality", "data quality")
        )

        lines.extend([
            "Why:",
            explanation,
        ])

        return "\n".join(lines)

    # ========================================================
    # AUTOMATIC RECOVERY
    # ========================================================

    elif intent == "RECOVERY":

        print("[Router] Running Automatic Recovery")

        return get_recovery_report()

    # ========================================================
    # RECOVERY HISTORY
    # ========================================================

    elif intent == "RECOVERY_HISTORY":

        print("[Router] Showing Recovery History")

        return format_recovery_history()

    # ========================================================
    # LAST RECOVERY
    # ========================================================

    elif intent == "LAST_RECOVERY":

        print("[Router] Showing Last Recovery")

        event = get_last_recovery()

        # ----------------------------------------------------
        # No recovery history
        # ----------------------------------------------------

        if event is None:
            return (
                "📜 HOPE Recovery History\n\n"
                "No recovery events have been recorded yet."
            )

        # ----------------------------------------------------
        # Display latest recovery event
        # ----------------------------------------------------

        return (
            "🔧 Last HOPE Recovery\n"
            "\n"
            f"Time    : {event.get('time', 'Unknown')}\n"
            f"Module  : {event.get('module', 'Unknown')}\n"
            f"Failure : {event.get('failure', 'Unknown')}\n"
            f"Action  : {event.get('action', 'Unknown')}\n"
            f"Result  : {event.get('result', 'Unknown')}\n"
            f"Health  : "
            f"{event.get('health_before', 'Unknown')} → "
            f"{event.get('health_after', 'Unknown')}"
        )

    # ========================================================
    # HELP ENGINE
    # ========================================================

    elif intent == "HELP":

        # ----------------------------------------------------
        # Plain help
        # ----------------------------------------------------

        if command == "help":
            return show_help()

        # ----------------------------------------------------
        # Help aliases
        # ----------------------------------------------------

        if command in [
            "commands",
            "show commands",
            "available commands",
        ]:
            return show_help()

        # ----------------------------------------------------
        # Category help
        # ----------------------------------------------------

        parts = command.split(" ", 1)

        if len(parts) == 2:

            category = parts[1].strip()

            return show_help(category)

        return show_help()

    # ========================================================
    # MEMORY SAVE
    # ========================================================

    elif intent == "MEMORY_SAVE":

        if "key" in result and "value" in result:

            key = result["key"]
            value = result["value"]

        else:

            parts = command.split(" ", 2)

            if len(parts) != 3:
                return "Usage: remember <key> <value>"

            key = parts[1]
            value = parts[2]

        print("[Router] Saving Memory")
        print(f"[Router] Key   : {key}")
        print(f"[Router] Value : {value}")

        return remember(key, value)

    # ========================================================
    # MEMORY RECALL
    # ========================================================

    elif intent == "MEMORY_RECALL":

        parts = command.split(" ", 1)

        if len(parts) != 2:
            return "Usage: recall <key>"

        key = parts[1]

        print("[Router] Recalling Memory")
        print(f"[Router] Key : {key}")

        value = recall(key)

        if value is not None:
            return value

        return "I don't remember that."

    # ========================================================
    # MEMORY FORGET
    # ========================================================

    elif intent == "FORGET":

        parts = command.split(
            " ",
            1
        )

        if len(parts) != 2 or not parts[1].strip():
            return "Usage: forget <key>"

        key = parts[1].strip()

        print("[Router] Forgetting Memory")
        print(f"[Router] Key : {key}")

        result = forget(key)

        if result:
            return f"I've forgotten your {key}."

        return f"I don't have anything stored for {key}."

    # ========================================================
    # GOAL DETECTION
    # ========================================================

    elif intent == "GOAL":

        goal_result = process_goal(command)

        if goal_result is None:
            return "I couldn't identify your goal."

        goal = goal_result["goal"]

        return get_roadmap(goal)

    # ========================================================
    # GOAL RECALL
    # ========================================================

    elif intent == "GOAL_RECALL":

        goal = recall("current_goal")

        if goal is None:
            return "You haven't told me your goal yet."

        return (
            "🎯 Your current goal is:\n\n"
            f"{goal}"
        )

    # ========================================================
    # STUDY PLAN
    # ========================================================

    elif intent == "STUDY_PLAN":

        goal = recall("current_goal")

        if goal is None:
            return (
                "You haven't set a goal yet.\n\n"
                "Try saying:\n"
                "'I want to become AI Engineer'"
            )

        return get_today_plan(goal)

    # ========================================================
    # PROGRESS
    # ========================================================

    elif intent == "PROGRESS":

        goal = recall("current_goal")

        if goal is None:
            return "You haven't set a goal yet."

        return get_progress(goal)

    # ========================================================
    # NEXT TOPIC
    # ========================================================

    elif intent == "NEXT_TOPIC":

        goal = recall("current_goal")

        if goal is None:
            return "You haven't set a goal yet."

        topic = get_next_topic(goal)

        if topic is None:
            return (
                "🎉 Congratulations!\n"
                "You have completed your roadmap."
            )

        return (
            "📘 Your next topic is:\n\n"
            f"{topic}"
        )

    # ========================================================
    # MARK COMPLETED
    # ========================================================

    elif intent == "MARK_COMPLETED":

        goal = recall("current_goal")

        if goal is None:
            return "You haven't set a goal yet."

        topic = (
            command
            .replace("mark", "", 1)
            .replace("completed", "", 1)
            .strip()
            .title()
        )

        if not topic:
            return "Usage: mark <topic> completed"

        message = mark_completed(goal, topic)

        progress = get_progress(goal)

        return (
            f"{message}\n\n"
            f"{progress}"
        )

    # ========================================================
    # LAST USER MESSAGE
    # ========================================================

    elif intent == "LAST_USER_MESSAGE":

        last_message = get_last_user_message(
            skip_current=True
        )

        if last_message:
            return f'You said: "{last_message}"'

        return "I don't remember you saying anything yet."

    # ========================================================
    # CONVERSATION SUMMARY
    # ========================================================

    elif intent == "CONVERSATION_SUMMARY":

        return summarize_conversation()

    # ========================================================
    # KNOWLEDGE SEARCH
    # ========================================================

    elif intent == "KNOWLEDGE_SEARCH":

        response = reason(command)

        if response is not None:
            return response

        return search_knowledge(command)

    # ========================================================
    # COMPARISON
    # ========================================================

    elif intent == "COMPARE":

        response = reason(command)

        if response is not None:
            return response

        return "I couldn't compare those topics."

    # ========================================================
    # RECOMMENDATION
    # ========================================================

    elif intent == "RECOMMEND":

        response = reason(command)

        if response is not None:
            return response

        return "I don't have a recommendation."

    # ========================================================
    # EXIT
    # ========================================================

    elif intent == "EXIT":

        return "Goodbye!"

    # ========================================================
    # UNKNOWN
    # ========================================================

    else:

        return process_command(command)
